; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Smart Desktop"
#define MyAppVersion "1.0"
#define MyAppPublisher "Guillaume VALENTIN"
#define MyAppURL "https://github.com/Azimut-Studio/smart-desktop/blob/main/README.md"
#define MyAppExeName "SmartDesktop.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A054EE0F-4514-43AF-A6CA-491788405D1D}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=E:\VSCodeProjects\smart-desktop\installer
OutputBaseFilename=SmartDesktop_installer
SetupIconFile=E:\VSCodeProjects\smart-desktop\assets\smart-desktop.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "french"; MessagesFile: "compiler:Languages\French.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "E:\VSCodeProjects\smart-desktop\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: filesandordirs; Name: "{localappdata}\SmartDesktop"; Check: ShouldDeleteUserData

[Code]
var
  DeleteUserData: Boolean;

function GetCurrentProcessId: DWORD;
  external 'GetCurrentProcessId@kernel32.dll stdcall';

function ProcessIdToSessionId(ProcessId: DWORD; var SessionId: DWORD): BOOL;
  external 'ProcessIdToSessionId@kernel32.dll stdcall';

function ShouldDeleteUserData: Boolean;
begin
  Result := DeleteUserData;
end;

function InitializeUninstall: Boolean;
var
  SessionId: DWORD;
  ResultCode: Integer;
begin
  Result := False;

  DeleteUserData :=
    MsgBox(
      'Souhaitez-vous également supprimer les sauvegardes, paramètres et journaux locaux de Smart Desktop dans :' + #13#10#13#10 +
      ExpandConstant('{localappdata}\SmartDesktop') + ' ?',
      mbConfirmation, MB_YESNO or MB_DEFBUTTON2) = IDYES;

  if not ProcessIdToSessionId(GetCurrentProcessId, SessionId) then
  begin
    MsgBox('Impossible de déterminer la session Windows pour arrêter Smart Desktop.', mbError, MB_OK);
    Exit;
  end;

  if not Exec(
    ExpandConstant('{sys}\taskkill.exe'),
    '/FI "SESSION eq ' + IntToStr(SessionId) + '" /IM {#MyAppExeName} /T /F',
    '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
  begin
    MsgBox(
      'Impossible de lancer l''arrêt de Smart Desktop :' + #13#10 + SysErrorMessage(ResultCode),
      mbError, MB_OK);
    Exit;
  end;

  if (ResultCode <> 0) and (ResultCode <> 128) then
  begin
    MsgBox(
      'Impossible d''arrêter Smart Desktop (code ' + IntToStr(ResultCode) + ').' + #13#10 +
      'Fermez l''application puis relancez la désinstallation.',
      mbError, MB_OK);
    Exit;
  end;

  Result := True;
end;
